version: "3.8"

services:
  # 백엔드 API 서버
  insure-crm-api:
    build: .
    container_name: insure-crm-backend
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - FRONTEND_URL=http://localhost:3001
    # volumes:
    # 개발 시에만 활성화 (라이브 리로드)
    # - .:/app
    # - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/auth/register"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - insure-network

  # 개발용 데이터베이스 (선택사항)
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: insure-postgres
  #   environment:
  #     POSTGRES_DB: insure_crm
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - insure-network

networks:
  insure-network:
    driver: bridge
# volumes:
#   postgres_data:
